# Generated by Django 3.2.8 on 2021-10-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='invoice_date',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateField(verbose_name='Paid Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='complete_date',
            field=models.DateField(blank=True, verbose_name='Date Complete'),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_date',
            field=models.DateField(verbose_name='Date Identified'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='Start Date'),
        ),
    ]
